# Generated by Django 3.1 on 2020-08-16 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_applications_posts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='applications',
        ),
        migrations.AddField(
            model_name='applications',
            name='job_id',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='apis.posts'),
        ),
        migrations.AddField(
            model_name='applications',
            name='resume',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
