# Generated by Django 3.1 on 2020-08-16 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0003_auto_20200816_1102'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applications',
            old_name='note',
            new_name='notes',
        ),
    ]
