# Generated by Django 3.1 on 2020-08-16 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0004_auto_20200816_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
