# Generated by Django 3.1 on 2020-08-10 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_application'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='resume',
        ),
        migrations.AddField(
            model_name='application',
            name='resume_file_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
